---
version: "3.3"
services:
  redis:
    container_name: animalwiki-redis
    image: redis:alpine
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./enumerate.redis:/root/enumerate.redis
      - ./enumerate.sh:/root/enumerate.sh
    entrypoint: sh -c "sh /root/enumerate.sh"
    expose:
      - "6379"
    ports:
      - "6379:6379"
