---
version: "3.3"
services:
  redis:
    container_name: animalwiki-redis
    image: redis:alpine
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - animalwiki-data:/data
    command: ["redis-server", "/etc/redis/redis.conf", "--loglevel warning", "--appendonly yes"]
    ports:
      - "6379:6379"
    networks:
      - animalwiki
    restart: unless-stopped
  
  rediscommander:
    container_name: rediscommander
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379:0:password
    networks:
      - animalwiki
    restart: unless-stopped

volumes:
  animalwiki-data:
    name: animalwiki-data
networks:
  animalwiki:
    name: animalwiki